build:
  stage: build
  script:
    - shopt -s extglob
    - shopt -s dotglob
    - mv playground_application playground_application_temp
    - mkdir playground_application
    - mv !(playground_application) playground_application
    - mv playground_application/playground_application_temp playground_application/playground_application
    - cp -r /Users/Norbz/Documents/Imperial/4th-Year/Individual-Project/feedback_driven_development/feedback_wrapper .
    - cp -r /Users/Norbz/Documents/Imperial/4th-Year/Individual-Project/feedback_driven_development/Dockerfile .
#    - docker build --tag=playground_application .
    - docker build --tag=playground_application DockerfileUber
deploy:
  stage: deploy
  script:
    - docker stop playground_application_prod || true
    - docker container rm playground_application_prod || true
    - docker run --detach --cap-add=SYS_PTRACE -p 4001:8081 --name playground_application_prod playground_application
  only:
    - master
