build:
  stage: build
  script:
    - shopt -s extglob
    - shopt -s dotglob
    - mv playground_application playground_application_temp
    - mkdir playground_application
    - mv !(playground_application) playground_application
    - mv playground_application/playground_application_temp playground_application/playground_application
    - sudo cp -r /home/np1815/Individual-Project/feedback_driven_development/feedback_wrapper .
    - sudo chmod -R 0777 .
deploy:
  stage: deploy
  script:
    - sudo kill $RUNNING_SERVER && true
    - sudo cd /home/np1815/Individual-Project/feedback_driven_development/playground_application
    - sudo ./run_gunicorn.sh &
    - sudo export RUNNING_SERVER=$1
  only:
    - master
