openapi: 3.0.0
info:
  title: Playground Application
  version: 0.0.1
servers:
- url: http://localhost:4000/api
- url: http://localhost:8081/api
paths:
  /one:
    get:
      description: The one.
      operationId: playground_application.controllers.default_controller.one_get
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Number'
          description: "1"
      summary: One.
  /two:
    get:
      description: The two.
      operationId: playground_application.controllers.default_controller.two_get
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Number'
          description: "2"
      summary: Two.
  /three:
    get:
      description: The three.
      operationId: playground_application.controllers.default_controller.three_get
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Number'
          description: "3"
      summary: Three.
  /load:
    get:
      description: Load something in pandas.
      operationId: playground_application.controllers.default_controller.load
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoadedCsv'
          description: "3"
      summary: Load.
  /list_comprehension:
    get:
      description: List comprehension.
      operationId: playground_application.controllers.default_controller.list_comprehension
      responses:
        200:
          description: 'List comprehension'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfNumbers'
components:
  schemas:
    Number:
      type: object
      properties:
        i:
          format: int32
          type: integer
      required:
      - i
    LoadedCsv:
      type: object
      properties:
        rows:
          additionalProperties:
            items:
              format: float
              type: number
            type: array
          type: object
      required:
      - rows
    ListOfNumbers:
      type: array
      items:
        $ref: '#/components/schemas/Number'
