openapi: 3.0.0
info:
  title: Playground Application
  version: 0.0.1
servers:
- url: http://localhost:4000/uber
- url: http://localhost:8081/uber
paths:
  /find_ride:
    post:
      description: Find a ride.
      summary: One.
      operationId: playground_application.controllers.uber_controller.find_ride
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FindRideRequest'
      responses:
        200:
          description: Ride information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindRideResponse'
components:
  schemas:
    Location:
      type: object
      properties:
        x:
          type: integer
        y:
          type: integer
    Driver:
      type: object
      properties:
        current_location:
          $ref: '#/components/schemas/Location'
        rating:
          type: integer
    FindRideRequest:
      type: object
      properties:
        start_location:
          $ref: '#/components/schemas/Location'
        end_location:
          $ref: '#/components/schemas/Location'
    FindRideResponse:
      type: object
      properties:
        driver:
          $ref: '#/components/schemas/Driver'
        estimated_cost:
          type: number
          format: double