# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playground_application.models.base_model_ import Model
from playground_application.models.location import Location
from playground_application import util

from playground_application.models.location import Location  # noqa: E501

class Driver(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_location=None, rating=None):  # noqa: E501
        """Driver - a model defined in OpenAPI

        :param current_location: The current_location of this Driver.  # noqa: E501
        :type current_location: Location
        :param rating: The rating of this Driver.  # noqa: E501
        :type rating: int
        """
        self.openapi_types = {
            'current_location': Location,
            'rating': int
        }

        self.attribute_map = {
            'current_location': 'current_location',
            'rating': 'rating'
        }

        self._current_location = current_location
        self._rating = rating

    @classmethod
    def from_dict(cls, dikt) -> 'Driver':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Driver of this Driver.  # noqa: E501
        :rtype: Driver
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_location(self):
        """Gets the current_location of this Driver.


        :return: The current_location of this Driver.
        :rtype: Location
        """
        return self._current_location

    @current_location.setter
    def current_location(self, current_location):
        """Sets the current_location of this Driver.


        :param current_location: The current_location of this Driver.
        :type current_location: Location
        """

        self._current_location = current_location

    @property
    def rating(self):
        """Gets the rating of this Driver.


        :return: The rating of this Driver.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """Sets the rating of this Driver.


        :param rating: The rating of this Driver.
        :type rating: int
        """

        self._rating = rating
