# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playground_application.models.base_model_ import Model
from playground_application.models.driver import Driver
from playground_application import util

from playground_application.models.driver import Driver  # noqa: E501

class FindRideResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, driver=None, estimated_cost=None):  # noqa: E501
        """FindRideResponse - a model defined in OpenAPI

        :param driver: The driver of this FindRideResponse.  # noqa: E501
        :type driver: Driver
        :param estimated_cost: The estimated_cost of this FindRideResponse.  # noqa: E501
        :type estimated_cost: float
        """
        self.openapi_types = {
            'driver': Driver,
            'estimated_cost': float
        }

        self.attribute_map = {
            'driver': 'driver',
            'estimated_cost': 'estimated_cost'
        }

        self._driver = driver
        self._estimated_cost = estimated_cost

    @classmethod
    def from_dict(cls, dikt) -> 'FindRideResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindRideResponse of this FindRideResponse.  # noqa: E501
        :rtype: FindRideResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def driver(self):
        """Gets the driver of this FindRideResponse.


        :return: The driver of this FindRideResponse.
        :rtype: Driver
        """
        return self._driver

    @driver.setter
    def driver(self, driver):
        """Sets the driver of this FindRideResponse.


        :param driver: The driver of this FindRideResponse.
        :type driver: Driver
        """

        self._driver = driver

    @property
    def estimated_cost(self):
        """Gets the estimated_cost of this FindRideResponse.


        :return: The estimated_cost of this FindRideResponse.
        :rtype: float
        """
        return self._estimated_cost

    @estimated_cost.setter
    def estimated_cost(self, estimated_cost):
        """Sets the estimated_cost of this FindRideResponse.


        :param estimated_cost: The estimated_cost of this FindRideResponse.
        :type estimated_cost: float
        """

        self._estimated_cost = estimated_cost
