# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playground_application.models.base_model_ import Model
from playground_application.models.location import Location
from playground_application import util

from playground_application.models.location import Location  # noqa: E501

class FindRideRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start_location=None, end_location=None):  # noqa: E501
        """FindRideRequest - a model defined in OpenAPI

        :param start_location: The start_location of this FindRideRequest.  # noqa: E501
        :type start_location: Location
        :param end_location: The end_location of this FindRideRequest.  # noqa: E501
        :type end_location: Location
        """
        self.openapi_types = {
            'start_location': Location,
            'end_location': Location
        }

        self.attribute_map = {
            'start_location': 'start_location',
            'end_location': 'end_location'
        }

        self._start_location = start_location
        self._end_location = end_location

    @classmethod
    def from_dict(cls, dikt) -> 'FindRideRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindRideRequest of this FindRideRequest.  # noqa: E501
        :rtype: FindRideRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_location(self):
        """Gets the start_location of this FindRideRequest.


        :return: The start_location of this FindRideRequest.
        :rtype: Location
        """
        return self._start_location

    @start_location.setter
    def start_location(self, start_location):
        """Sets the start_location of this FindRideRequest.


        :param start_location: The start_location of this FindRideRequest.
        :type start_location: Location
        """

        self._start_location = start_location

    @property
    def end_location(self):
        """Gets the end_location of this FindRideRequest.


        :return: The end_location of this FindRideRequest.
        :rtype: Location
        """
        return self._end_location

    @end_location.setter
    def end_location(self, end_location):
        """Sets the end_location of this FindRideRequest.


        :param end_location: The end_location of this FindRideRequest.
        :type end_location: Location
        """

        self._end_location = end_location
